name: poli__pr
channels:
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pip
  - pip:
      - numpy<2
      - torch
      - gpytorch==1.11
      - botorch==0.7.0
      - scipy
      - jupyter
      - matplotlib
      - nevergrad
      - scikit-learn
      - statsmodels
      - xgboost
      - black
      - "git+https://github.com/miguelgondu/bo_pr.git@main"
      - "git+https://github.com/MachineLearningLifeScience/poli.git@v0.2.1"
      - "git+https://github.com/MachineLearningLifeScience/poli-baselines.git@main"

