name: poli__boss
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy<2
    - emukit
    - pandas>=1.5.3,<1.6.0
    - coverage>=7.2.5,<7.3.0
    - requests>=2.31.0,<2.32.0
    - black>=22.12.0,<22.13.0
    - memray>=1.6.0,<1.7.0
    - pytest>=7.3.1,<7.4.0
    - "git+https://github.com/MachineLearningLifeScience/poli.git@v0.2.1"
    - "git+https://github.com/MachineLearningLifeScience/poli-baselines@main"
    - "git+https://github.com/miguelgondu/bounce.git@main"
