name: poli__baxus
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - baxus
    - "git+https://github.com/MachineLearningLifeScience/poli.git@dev"
    - "git+https://github.com/MachineLearningLifeScience/poli-baselines@main"
