name: poli__ax
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - ax-platform
    - numpy
    - "git+https://github.com/MachineLearningLifeScience/poli.git@dev"
    - "git+https://github.com/MachineLearningLifeScience/poli-baselines@main"
    - "git+https://github.com/miguelgondu/bounce.git@main"
