defaults:
  - tree: sequence_model_conservative
  - roots: [protein_seq]
  - trunk: sum_trunk
  - branches: [protein_property, protein_generation]
  - tasks:
    - generic_task
    - protein_seq
  - guidance_objective: generic_task
  - optim: lambo_conservative

feature_dim: 32
kernel_size: 3
batch_size: 32
max_epochs: 1
data_dir: ./.cache
wandb_mode: offline
random_seed: 42
num_steps: 1
num_samples: 16
allow_length_change: false

trainer:
  _target_: lightning.Trainer
  max_epochs: ${max_epochs}
  num_sanity_val_steps: 1
