defaults:
  - tree: sequence_model_conservative
  - roots: [protein_seq]
  - trunk: sum_trunk
  # - branches: [protein_property, protein_generation, protein_constraint]
  - branches: [protein_property, protein_generation]
  - tasks:
    # - generic_constraint
    - generic_task
    - protein_seq
  - guidance_objective: generic_task
  - optim: lambo_conservative

feature_dim: 128
kernel_size: 3
batch_size: 128
max_epochs: 1
data_dir: ./.cache
wandb_mode: offline
random_seed: 42
num_steps: 1
num_samples: ${batch_size}
allow_length_change: false

trainer:
  _target_: lightning.Trainer
  max_epochs: ${max_epochs}
  num_sanity_val_steps: 0
  accelerator: gpu
  devices: 1
  precision: 16
