name: LaMBO2 (py3.10 in conda)

on:
  push:
    branches:
      - main # Change this to your main branch name
  schedule:
    - cron: "0 0 * * 0" # This will run every Sunday at midnight UTC
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    if: github.event.pull_request.draft == false
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          python -m pip install tox
      - name: Test the LaMBO2 solver with tox
        run: |
          tox -e poli-lambo2-base-py310
